### ISSUE TITLE
LoadSection<T> fails after update

### ISSUE THREAD

**Issue by mattiasnordqvist** [mikeobrien/SimpleConfig#4]
After i updated my depencencies like this: 
SimpleConfig 1.0.38 -> 1.0.39
Bender 3.0.35 -> 3.0.41
Flexo 1.0.22 -> 1.0.23

LoadSection fails when the section to be loaded has an enum-property with a value defined in config with differing casing. 

My config:

`<ApiConfiguration Mode="dev"></ApiConfiguration>`

My code:

```csharp
public enum Mode
{
    Dev,
    Prod
}

public class ApiConfiguration
{
    public Mode Mode { get; set; }
}
```

Everything works again if I change my config to `<ApiConfiguration Mode="Dev"></ApiConfiguration>`, so it seems some case-sensitivity sneaked in somewhere in these updates.

**Comment by mikeobrien** [comment]
Doh, enum casing was made configurable in Bender but I forgot to set the default explicitly to match the old behavior. O_o That has been fixed and pushed, just update the Bender nuget (3.0.43) and you should be good to go. Sorry about that and thx for catching/reporting it!
