### ISSUE TITLE
must have a section handler of type 'SimpleConfig.Section'

### ISSUE THREAD

**Issue by neilw1** [mikeobrien/SimpleConfig#5]
Hello,
Just to be sure it is ok, I first created the entry in my app.config exactly as the example and then I created the MyApplication/Buillder exactly as the example.

All I get is 'The configuration section 'myApplication' must have a section handler of type 'SimpleConfig.Section'.

Any ideas?

btw, it might be useful to explicitly state in the github home page instructions you have to download and install Bender as it isn't in with the package and you end up with a weird namespace and dsl serialisation error.

Thanks.

**Comment by mikeobrien** [comment]
You'll have to post your config and code.

Bender is a [dependency of SimpleConfig](https://github.com/mikeobrien/SimpleConfig/blob/master/SimpleConfig.nuspec#L19) so should be downloaded automatically by Nuget but that version is old and it sounds like installing the oldest version it can instead of the newest version. I'll take a look.

**Comment by neilw1** [comment]
Thanks. Here's everything. When I searched nuget, version 1.0.40.0 came down. I downloaded Bender version 3.0.43.0

<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <appSettings>
  </appSettings>
  <startup>
    <supportedRuntime version="v4.5" sku=".NETFramework,Version=v4.5"/>
  </startup>
  <configSections>
    <section name="myApplication" type="SimpleConfig.Section, SimpleConfig" />
  </configSections>
  <myApplication>
    <build name="Default" brightness="-20" contrast="0" saturation="0" hue="0" opacity="0"/>
  </myApplication>
  
  <system.windows.forms jitDebugging="true" />
</configuration>

var config1 = SimpleConfig.Configuration.Load<MyApplication>();
//I did create my own names first, but that didn't work...
//ImageToolPresets myConfig = SimpleConfig.Configuration.Load<ImageToolPresets>("imageToolPresets");

    public class MyApplication
    {
        public Build Build { get; set; }
    }

    public class Build
    {
        public string Name;
        public string Brightness;
        public string Contrast;
        public string Saturation;
        public string Hue;
        public string Opacity;
    }

**Comment by mikeobrien** [comment]
Can you include your config too?

**Comment by neilw1** [comment]
I did, in the post I included everything:

<configuration>
  <appSettings>
  </appSettings>
  <startup>
    <supportedRuntime version="v4.5" sku=".NETFramework,Version=v4.5"/>
  </startup>
  <configSections>
    <section name="myApplication" type="SimpleConfig.Section, SimpleConfig" />
  </configSections>
  <myApplication>
    <build name="Default" brightness="-20" contrast="0" saturation="0" hue="0" opacity="0"/>
  </myApplication>

  <system.windows.forms jitDebugging="true" />
</configuration>

**Comment by mikeobrien** [comment]
Its not coming through, you'll have wrap it in a fenced code block or indent it 4 spaces for it to show up.

**Comment by neilw1** [comment]
I can see it in this web page :) here it is again...

START
```
<configuration>
<appSettings>
</appSettings>
<startup>
  <supportedRuntime version="v4.5" sku=".NETFramework,Version=v4.5"/>
</startup>
<configSections>
  <section name="myApplication" type="SimpleConfig.Section, SimpleConfig" />
</configSections>
<myApplication>
  <build name="Default" brightness="-20" contrast="0" saturation="0" hue="0" opacity="0"/>
</myApplication>

<system.windows.forms jitDebugging="true" />
</configuration>

```
END

**Comment by neilw1** [comment]
[SimpleConfigTest.txt](https://github.com/mikeobrien/SimpleConfig/files/309797/SimpleConfigTest.txt)

**Comment by neilw1** [comment]
Hello,
I've found the problem, but no idea how to fix it. So, it's not your code anyway :)

This is a class library, my class library is definitely reading the file.dll.config file but it generates the error as stated above. If I move it to a console application it works.

**Comment by mikeobrien** [comment]
K, couple of things, `configSections` needs to be the first element after the opening `configuration` element. And second you're using fields which are not deserialized by default (as typically people use properties). I enabled fields by default so it should work out of the box now. Update and you should be good to go.

**Comment by neilw1** [comment]
cheers. I noticed the missing getter/setter, but that just caused null values but still worked in my console app. I moved the configSections to the top of the file, but it still doesn't want to work.

Is there something different with class libraries? I know it's reading the config file as I have other simple settings in this file.

Thanks for your help.

**Comment by neilw1** [comment]
Hello,
I've found the problem. No idea how to fix it. This is a class library, and calls to the app settings of it's config file work just fine, but it is not reading the configSections item as configuration items.

If I move it to a temporary console app.config that uses this class library it works.

Any idea how to fix this, as the class library is a standalone dll and the config file comes with it.

**Comment by mikeobrien** [comment]
Are you naming your config file the same as your assembly a la `MyLibrary.dll.config`?

**Comment by neilw1** [comment]
Yes. I have other items in the config file that read fine. I literally moved the entry into a test console app and it worked.

**Comment by neilw1** [comment]
Actually, I think I know the problem, which means there is no solution unless there's a way to register your class and config section in code rather than through the configSections entry?

In my code I have to tell it through reflection to manually load a ExeConfigurationFileMap and give it the path to the dll found through reflection, which means it's not really loaded by the system.

**Comment by mikeobrien** [comment]
Added an overload of `Load<T>()` that takes a `ExeConfigurationFileMap`. Should be out on the nuget gallery in about 10 minutes.

**Comment by chucklepie** [comment]
Thanks, you are a gent :)

I'll try it in the morning.

**Comment by chucklepie** [comment]
Hello,
Thanks for all your effort in helping. I have it working now :), but not with the exeMapfile.

After realising what the code did and how it worked (it was late for me), I realised you can pass in a filepath to the config file (I thought it was some config file auto-magic at first), and this works, however using the use exeFileMap all it does is give me an error. I can see your code change and it should work...

```
   string file = System.Reflection.Assembly.GetAssembly(typeof(PhotoComparison)).Location + ".config";
   ExeConfigurationFileMap cfm = new ExeConfigurationFileMap() { ExeConfigFilename = file };

   //works
   var filters1 = new SimpleConfig.Configuration(configPath: file).LoadSection<MyApplication>("presetFilters");

   //fails with no Section.Config for presetFilters error
   var filters2 = new SimpleConfig.Configuration(exeFileMap: cfm).LoadSection<MyApplication>("presetFilters");
```

As you can see, both are identical, but the second option always gives the Secion.Config missing error

**Comment by mikeobrien** [comment]
Ah ok, I'll throw a unit test in there for that and see if I can figure out
the issue. Glad it's working for you with the path.
